### ISSUE TITLE
Oiê

### ISSUE THREAD

**Issue by OrionRandD** [BuddhiLW/Frank-init#1]
Olá,
Emacs serve para tudo - ou quase tudo mesmo...
Até para ensinar Teologia e Filosofia...
https://mark.nl.tab.digital/s/qDo4sQwRkHjJrfq
;)

**Comment by BuddhiLW** [comment]
Oi, Orion! Tudo bem?

Realmente, muito poderoso para criar uma rede de arquivos e ideias organizadamente.

Você tá utilizando o _Frank-init_? 

Abraço!

**Comment by OrionRandD** [comment]
> Oi, Orion! Tudo bem?
> 
> Realmente, muito poderoso para criar uma rede de arquivos e ideias organizadamente.
> 
> Você tá utilizando o _Frank-init_?
> 
> Abraço!

Não. Eu tenho 3 Emacsen: Minha própria configuração, scimax (como minhas adicões) e Doom (com minhas adições)...

**Comment by BuddhiLW** [comment]
Pois é, verdade. Mas, aposto que a moda de VScode vai passar; provavelmente um novo editor "completo" surgirá. E, Emacs, Vim, continuarão vivos.

Eu sou um programador novo, comecei a programar há 4, 5 anos. O que me levou ao Emacs foi que estava aprendendo Common Lisp. Nunca mais larguei.

Entendi, tens a suas próprias confs. Bem, seja bem-vindo ao meu repositório. E, se quiser conversar qualquer hora, me chama no meu e-mail, pedrogbranquinho@gmail.com

**Comment by OrionRandD** [comment]
Ok...
Conseguiu aprender CL?
Blz...
Bom saber que há mais pessoas que usam Emacs nas terras
tupiniquins...
Tem um grupo de Chilenos estudando lisp através do Emacs no telegram.
O professor é muito bom...
Public Link: https://t.me/orgmdode_narval
Caso queira participar e conhecer...
A língua do canal é Espanhol...

**Comment by BuddhiLW** [comment]
Olha, aprendi o básico de CL. Me ajudou bastante quando parti para Clojure!

Interessante, vou entrar no grupo, sim. 

Abraços!
